import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import MyNavbar from "@/components/MyNavbar";
import localFont from "next/font/local";
import Footer from "@/components/Footer";
import { GoogleAnalytics } from '@next/third-parties/google';
import Script from 'next/script';

// 获取 Google Analytics ID
const GA_ID = process.env.NEXT_PUBLIC_GA_ID || '';

// 定义 Merriweather 字体
const Merriweather = localFont({
  src: [
    {
      path: './fonts/Merriweather-Regular.ttf',
      style: 'normal',
    },
  ],

  variable: '--font-merriweather',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* ✅ 插入 Google AdSense 脚本 */}
        <Script
          id="adsense-script"
          async
          strategy="afterInteractive"
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5943172736337554"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`${Merriweather.variable} antialiased`}>
        <ThemeProvider>
          <MyNavbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
      <GoogleAnalytics gaId={GA_ID}/>
    </html>
  );
}
