// components/landing/HowItWorks.tsx
import Image from "next/image";

export default function BedroomHowItWorksSection() {
  return (
    <section className="w-full flex flex-col text-start border-t border-default-200 pt-10 pb-5 gap-4 scroll-mt-24" id="how-it-works">
      <h2 className="text-3xl md:text-4xl font-bold">
        How the <span className="text-primary">AI Feng Shui Bedroom Tool</span> Works
      </h2>

      <div className="w-full mx-auto space-y-16 mt-4">

        {/* Step 1 */}
        <div className="flex flex-col md:flex-row items-start gap-8">
          {/* Text */}
          <div className="flex-1 space-y-4">
            <div className="text-3xl">📤</div>
            <h3 className="text-xl font-semibold">1. Upload Your Bedroom Layout</h3>
            <p className="text-default-600 text-base">
              Upload a clear image of your <strong>bedroom layout</strong> — a floor plan or neatly drawn sketch. Be sure to include the <strong>bed position</strong>, <strong>door</strong>, <strong>windows</strong>, and optionally the <strong>north direction</strong>. The more detail, the more accurate the <strong>bedroom feng shui analysis</strong>.
            </p>
          </div>
          {/* Image */}
          <div className="flex-1">
            <Image
              src="/images/how-to-1.png"
              alt="Upload Bedroom Layout for Feng Shui Evaluation"
              width={800}
              height={426}
              className="w-full"
            />
          </div>
        </div>

        {/* Step 2 */}
        <div className="flex flex-col md:flex-row-reverse items-start gap-8">
          {/* Text */}
          <div className="flex-1 space-y-4">
            <div className="text-3xl">🧭</div>
            <h3 className="text-xl font-semibold">2. Add Bedroom Info</h3>
            <p className="text-default-600 text-base">
              Tell us more about your bedroom — how it&apos;s used (e.g., main bedroom or guest room), and share any specific concerns or goals (like poor sleep, low energy, or relationship issues). This helps the <strong>AI Feng Shui system</strong> focus on what matters most to you and give personalized advice.
            </p>
          </div>
          {/* Image */}
          <div className="flex-1">
            <Image
              src="/images/how-to-2.png"
              alt="Add Bedroom Details and Orientation for Feng Shui"
              width={800}
              height={426}
              className="w-full rounded-lg shadow-md"
            />
          </div>
        </div>

        {/* Step 3 */}
        <div className="flex flex-col md:flex-row items-start gap-8">
          {/* Text */}
          <div className="flex-1 space-y-4">
            <div className="text-3xl">🔮</div>
            <h3 className="text-xl font-semibold">3. Get Your Feng Shui Bedroom Report</h3>
            <p className="text-default-600 text-base">
              The <strong>AI Feng Shui Generator</strong> analyzes your bedroom’s layout to check <strong>bed direction</strong>, <strong>door alignment</strong>, <strong>mirror position</strong>, and <strong>energy flow</strong>. You’ll receive personalized suggestions to improve <strong>sleep quality</strong>, <strong>emotional harmony</strong>, and overall <strong>feng shui balance</strong>.
            </p>
          </div>
          {/* Image */}
          <div className="flex-1">
            <Image
              src="/images/how-to-3.png"
              alt="Feng Shui Bedroom Report Generated by AI"
              width={800}
              height={426}
              className="w-full rounded-lg shadow-md"
            />
          </div>
        </div>
      </div>
    </section>
  );
}